#!/usr/bin/env ruby

require "json"
require "fileutils"
require "uri"
require "time"

SCRIPT_DIR = __dir__
PROJECT_ROOT = File.expand_path("..", SCRIPT_DIR)
REPO_ROOT = File.expand_path("..", PROJECT_ROOT)
SOURCE_HTML = File.join(PROJECT_ROOT, "王璐语料库_源码.html")
JSON_OUTPUT = File.join(REPO_ROOT, "data", "generated", "manifests", "listening_word_audio_index.json")
JS_OUTPUT = File.join(REPO_ROOT, "data", "generated", "inline", "listening_word_audio_data.js")
AUDIO_BASE_URL = "http://www.1kao.com.cn/iSpell/Spell/audio"

def extract_chapter_word_sets(html)
  match = html.match(/const CHAPTER_WORD_SETS = (\{[\s\S]*?\n\});\n\s*const EXPORT_FILE_PREFIX/)
  raise "未能从 HTML 中提取 CHAPTER_WORD_SETS。" unless match

  JSON.parse(match[1])
end

def build_entries(chapter_word_sets)
  chapter_word_sets
    .sort_by { |chapter_id, _chapter| chapter_id.to_i }
    .flat_map do |chapter_id, chapter|
      chapter_title = chapter.fetch("title", "")
      words = Array(chapter["words"])
      words.map do |word|
        clean_word = word.to_s.strip
        encoded_chapter = encode_component(chapter_id)
        encoded_word = encode_component(clean_word)
        remote_mp3 = "#{AUDIO_BASE_URL}/#{encoded_chapter}/#{encoded_word}.mp3"
        {
          "单词名" => clean_word,
          "mp3路径" => remote_mp3,
          "word" => clean_word,
          "mp3Path" => remote_mp3,
          "chapterId" => chapter_id,
          "chapterTitle" => chapter_title
        }
      end
    end
end

def encode_component(value)
  URI.encode_www_form_component(value.to_s).gsub("+", "%20")
end

def write_json(file_path, payload)
  FileUtils.mkdir_p(File.dirname(file_path))
  File.write(file_path, JSON.pretty_generate(payload))
end

def write_js(file_path, payload)
  FileUtils.mkdir_p(File.dirname(file_path))
  js = <<~JS
    // Auto-generated by listening-word/scripts/export_audio_index.rb
    // Do not edit manually.
    window.LISTENING_WORD_AUDIO_DATA = #{JSON.generate(payload)};
  JS
  File.write(file_path, js)
end

html = File.read(SOURCE_HTML)
chapter_word_sets = extract_chapter_word_sets(html)
entries = build_entries(chapter_word_sets)

manifest = {
  "generatedAt" => Time.now.iso8601,
  "total" => entries.length,
  "items" => entries
}

write_json(JSON_OUTPUT, manifest)
write_js(JS_OUTPUT, entries)

puts "已生成 JSON: #{JSON_OUTPUT}"
puts "已生成 JS: #{JS_OUTPUT}"
puts "总条目: #{entries.length}"
