<script setup>
import { computed, ref, watch, nextTick } from 'vue';
import Select from 'primevue/select';
import MultiSelect from 'primevue/multiselect';
import SelectButton from 'primevue/selectbutton';
import Checkbox from 'primevue/checkbox';
import Icon from '../Icon.vue';
import ModuleNav from '../ModuleNav.vue';
import HeaderTools from '../HeaderTools.vue';
import { library } from './library.js';
import { useListening } from './useListening.js';
import './style.css';

const app = useListening();
const settings = ref(null);
const answerInput = ref(null);
const storageEstimate = ref(null);
const tabs = [{ id: 'practice', label: '语料练习', icon: 'headphones' }, { id: 'mistakes', label: '错词本', icon: 'star' }, { id: 'stats', label: '章节统计', icon: 'chart' }];
const saveLabel = computed(() => app.storage.state === 'error' ? '尚未保存' : app.storage.state === 'loading' ? '正在读取' : app.storage.state === 'saving' ? '正在保存' : '本地已保存');
const availableCount = library.words.filter((word) => word.audio).length;
const groupOptions = library.chapters.map((chapter) => ({ label: `Chapter ${chapter.id} · ${chapter.title}`, items: chapter.groups.map((group) => ({ value: group.id, label: `${group.id} · ${group.label}` })) }));
const practiceGroupOptions = [{ label: '自定义语料', items: [{ value: '', label: '自定义语料 · 手动粘贴' }] }, ...groupOptions];
const practiceGroups = practiceGroupOptions.flatMap((group) => group.items);
const rateOptions = [0.4, 0.6, 0.8, 1, 1.2, 1.4, 1.6, 1.8, 2].map((value) => ({ value, label: `${value}×` }));
const orderOptions = [{ value: 'sequence', label: '顺序播放' }, { value: 'random', label: '乱序播放' }];
const modeOptions = [{ value: 'dictation', label: '听写', icon: 'pen' }, { value: 'listen', label: '听音', icon: 'headphones' }];
const mistakeFilters = [{ value: 'all', label: '全部错词' }, { value: 'low', label: '正确率低于 60%' }, { value: 'high', label: '答错至少 3 次' }, { value: 'recent', label: '最近 7 天' }];
const sortOptions = [{ value: 'errorLevel', label: '按错误等级' }, { value: 'wrongCount', label: '按错误次数' }, { value: 'errorRate', label: '按正确率' }, { value: 'recent', label: '按最近时间' }];
const completed = computed(() => app.session.mode === 'listen' ? app.status === 'finished' ? app.session.items.length : app.session.index : app.session.answers.size);
const percent = computed(() => Math.round(completed.value / Math.max(1, app.session.items.length) * 100));
const graphRows = computed(() => app.scoreRows.slice(-14).map((row, index, rows) => ({ ...row, x: rows.length === 1 ? 320 : 44 + index * 552 / (rows.length - 1), y: 184 - (row.total ? row.correct / row.total : 0) * 152, accuracy: row.total ? Math.round(row.correct / row.total * 1000) / 10 : 0 })));
const graphPoints = computed(() => graphRows.value.map((row) => `${row.x},${row.y}`).join(' '));
const formatBytes = (bytes) => bytes < 1024 ? `${bytes} B` : `${(bytes / 1024).toFixed(1)} KiB`;
const accuracy = (record) => record?.practiceCount ? `${Math.round(record.correctCount / record.practiceCount * 100)}%` : '未听写';
watch(() => [app.current?.key, app.paused, app.prefs.view], async () => { await nextTick(); if (app.active && !app.paused && app.session.mode === 'dictation' && app.prefs.view === 'practice' && !app.answered) answerInput.value?.focus(); });
async function openSettings() {
  settings.value.showModal();
  try { storageEstimate.value = await navigator.storage?.estimate?.(); } catch { storageEstimate.value = null; }
}
function chooseChapter(id) { app.prefs.groupId = library.chapters.find((chapter) => chapter.id === id).groups[0].id; app.selectGroup(); }
</script>

<template>
  <div class="app-shell corpus-app">
    <header class="site-header"><div class="header-inner">
      <a class="brand" href="/words/study_words.html" aria-label="IELTS Studio，返回单词学习"><span class="brand-symbol"><Icon name="book" :size="22" /></span><span class="brand-name">IELTS<span>Studio</span></span></a>
      <ModuleNav active="listening" />
      <HeaderTools><button class="save-indicator" :class="{ error: app.storage.state === 'error', fallback: app.storage.mode === 'localStorage' }" @click="openSettings"><span class="status-dot"></span>{{ saveLabel }}</button></HeaderTools>
    </div></header>
    <main class="main-container">
      <div class="page-heading"><div><div class="eyebrow">LISTEN A LITTLE CLOSER</div><h1>听力语料库<span class="heading-dot">.</span></h1><p>从听清一个词，到听懂一段话。</p></div></div>
      <div class="workspace-nav"><nav class="page-nav" aria-label="听力模块导航"><button v-for="tab in tabs" :key="tab.id" :class="{ active: app.prefs.view === tab.id }" :aria-current="app.prefs.view === tab.id ? 'page' : undefined" @click="app.showView(tab.id)"><Icon :name="tab.icon" :size="17" />{{ tab.label }}<span v-if="tab.id === 'mistakes' && app.mistakes.length" class="nav-count">{{ app.mistakes.length }}</span></button></nav><span class="corpus-library-count">{{ library.groups.length }} 组<span>·</span>{{ library.words.length.toLocaleString() }} 条语料</span></div>
      <div v-if="app.storage.state === 'error'" class="storage-warning" role="alert"><Icon name="storage" /><p>{{ app.storage.message }}</p><button class="secondary-button" @click="app.retrySave">重试保存</button></div>
      <div v-if="app.storage.mode === 'localStorage' && app.storage.state !== 'error'" class="fallback-notice">当前使用兼容存储，容量较小。学习记录仍按词条和日期分开保存。</div>
      <div v-if="!app.ready" class="loading-state" role="status"><span class="loading-ring"></span>正在准备语料与学习记录……</div>
      <template v-else>
        <template v-if="app.prefs.view === 'practice'">
          <section class="corpus-selection selection-panel" aria-label="语料选择">
            <SelectButton class="corpus-chapters ui-pills" :model-value="app.group?.chapter" :options="library.chapters" option-label="title" option-value="id" :allow-empty="false" :disabled="app.active" aria-label="听力章节" @update:model-value="chooseChapter"><template #option="{ option }"><span class="ui-option-count">{{ String(option.id).padStart(2, '0') }}</span>{{ option.title }}</template></SelectButton>
            <div class="corpus-selection-row"><div class="corpus-group-field"><label for="corpusGroupSelect">选择分组</label><Select input-id="corpusGroupSelect" :model-value="practiceGroups.find(group => group.value === app.prefs.groupId)" :options="practiceGroupOptions" option-label="label" data-key="value" option-group-label="label" option-group-children="items" :disabled="app.active" filter filter-placeholder="搜索分组编号或名称" reset-filter-on-hide checkmark aria-label="选择分组" @update:model-value="app.prefs.groupId = $event.value" @change="app.selectGroup" /></div><SelectButton class="ui-segmented" :model-value="app.prefs.mode" :options="modeOptions" option-label="label" option-value="value" :allow-empty="false" :disabled="app.active" aria-label="练习模式" @update:model-value="app.setMode"><template #option="{ option }"><Icon :name="option.icon" :size="15" />{{ option.label }}</template></SelectButton><button class="primary-button corpus-start" :disabled="app.active" @click="app.start"><Icon name="play" :size="16" />{{ app.status === 'finished' ? '再练一轮' : '开始练习' }}</button></div>
            <div v-if="!app.group" class="corpus-custom"><label for="corpusWordInput">用分号、逗号或换行分隔语料，同一行可输入多条，自动去重并匹配词库</label><textarea id="corpusWordInput" v-model="app.customText" :disabled="app.active" maxlength="100000" rows="4" placeholder="ability, abstract, accountant" @blur="app.saveCustom"></textarea></div>
            <details v-else open class="corpus-custom corpus-edit-group"><summary>查看或调整本组语料<Icon name="down" :size="13" /></summary><label for="corpusGroupWordInput">同一行可输入多条，用分号、逗号或换行分隔；只匹配当前分组，部分语料练习不计完整章节成绩。</label><textarea id="corpusGroupWordInput" v-model="app.customText" :disabled="app.active" maxlength="100000" rows="4" @blur="app.saveCustom"></textarea><button class="text-button" :disabled="app.active" @click="app.selectGroup">恢复本组全部语料</button></details>
            <div class="corpus-config-summary"><span v-if="app.group">{{ app.group.items.length }} 条语料<span v-if="app.group.missing.length" class="corpus-missing"> · {{ app.group.missing.length }} 条缺少音频</span></span><span v-else>自定义列表不计完整章节成绩</span><span>{{ app.prefs.mode === 'dictation' ? '拼写判定，记录错词与成绩' : '专注听音，不记录听写成绩' }}</span></div>
            <details open class="corpus-options">
              <summary><Icon name="settings" :size="14" />播放设置<span>单词 {{ app.prefs.rate }}× · 词组 {{ app.prefs.phraseRate }}× · 间隔 {{ app.prefs.interval }} 秒</span><Icon name="down" :size="14" /></summary>
              <fieldset :disabled="app.active"><div class="corpus-settings-grid">
                <label for="corpusRate">单词倍速<Select input-id="corpusRate" v-model="app.prefs.rate" :options="rateOptions" option-label="label" option-value="value" :disabled="app.active" checkmark aria-label="单词倍速" @change="app.savePrefs" /></label>
                <label for="corpusPhraseRate">词组倍速<Select input-id="corpusPhraseRate" v-model="app.prefs.phraseRate" :options="rateOptions" option-label="label" option-value="value" :disabled="app.active" checkmark aria-label="词组倍速" @change="app.savePrefs" /></label>
                <label>每词间隔（秒）<input id="corpusInterval" v-model.number="app.prefs.interval" type="number" min="0" max="60" step="0.5" @change="app.savePrefs" /></label>
                <label for="corpusOrder">听音顺序<Select input-id="corpusOrder" v-model="app.prefs.order" :options="orderOptions" option-label="label" option-value="value" :disabled="app.active" checkmark aria-label="听音顺序" @change="app.savePrefs" /></label>
                <label for="corpusRepeat">单词循环次数<input id="corpusRepeat" v-model.number="app.prefs.repeat" type="number" min="1" step="1" @change="app.savePrefs" /></label>
                <label for="corpusLoops">大循环播放次数<input id="corpusLoops" v-model.number="app.prefs.loops" type="number" min="1" step="1" @change="app.savePrefs" /></label>
              </div></fieldset>
              <p>{{ app.prefs.mode === 'dictation' ? '听音顺序与循环次数用于听音模式。听写时，音频结束后按间隔计时，超时或显示答案记为错词；答对自动进入下一题。' : '每条语料按单词循环次数播放结束后，按间隔进入下一条；整组按大循环播放次数重复。' }}间隔为 0 时手动进入下一条。练习中可暂停，或结束后更换设置。</p>
            </details>
          </section>
          <p v-if="app.inputNotice" class="corpus-input-notice" role="status">{{ app.inputNotice }}</p>
          <div class="corpus-practice-layout">
            <section class="content-panel corpus-practice" aria-label="听力练习">
              <div class="corpus-stage-top"><span class="eyebrow">{{ app.session.mode === 'listen' && app.active ? 'JUST LISTEN' : 'LISTEN & SPELL' }}</span><span v-if="app.active">{{ app.session.index + 1 }} / {{ app.session.items.length }}<span v-if="app.session.loops > 1"> · 第 {{ app.session.loop }} / {{ app.session.loops }} 轮</span></span><span v-else>{{ app.status === 'finished' ? '本轮完成' : '准备开始' }}</span></div>
              <div v-if="app.status === 'idle'" class="corpus-idle"><span class="corpus-idle-icon"><Icon name="headphones" :size="38" /></span><h2>把每个词听清楚</h2><p>选择一组语料，开始听音或拼写练习。</p><div class="corpus-sound-bars" aria-hidden="true"><i v-for="height in [14, 27, 43, 30, 54, 38, 22, 46, 31, 16]" :key="height" :style="{ height: height + 'px' }"></i></div><span class="corpus-source-note">王璐语料库机考 2 版 · 本地原声语料</span></div>
              <div v-else-if="app.status === 'finished'" class="corpus-finished"><span class="corpus-finish-icon"><Icon name="check" :size="32" /></span><h2>{{ app.session.mode === 'listen' ? '这一轮，听完了' : '这一轮，练完了' }}</h2><p v-if="app.session.mode === 'listen'">已完成 {{ app.session.loops }} 轮听音，不记录听写成绩。</p><p v-else>{{ app.correctCount }} 条答对，{{ app.wrongItems.length }} 条需要再巩固<span v-if="app.session.skipped">，{{ app.session.skipped }} 条音频已跳过</span>。</p><p v-if="app.session.mode === 'dictation'" class="corpus-score-note">{{ app.session.full ? '完整章节成绩已计入统计。' : '本轮为子集、错词复练或包含音频跳过，不计完整章节成绩。' }}</p><button v-if="app.wrongItems.length" class="primary-button" @click="app.restartWrong"><Icon name="refresh" :size="16" />只练本轮错词</button><button class="text-button" @click="app.showView('stats')">查看章节统计<Icon name="right" :size="16" /></button></div>
              <template v-else>
                <p class="corpus-current-context">{{ app.current?.chapterTitle }} · {{ app.current?.groupTitle }}</p>
                <div class="corpus-active-stage"><button class="corpus-audio-button" :class="{ speaking: app.speaking }" aria-label="重播当前音频" @click="app.replay"><Icon name="volume" :size="33" /></button><h2 v-if="app.session.mode === 'listen' ? app.prefs.showCurrentWord : app.answered" id="corpusCurrentWord" class="corpus-current-word">{{ app.current?.word }}</h2><h2 v-else>{{ app.session.mode === 'listen' ? '让耳朵记住这个词' : '听一听，写下来' }}</h2><button v-if="app.session.mode === 'listen'" class="text-button corpus-word-toggle" :aria-pressed="app.prefs.showCurrentWord" @click="app.toggleCurrentWord"><Icon name="eye" :size="15" />{{ app.prefs.showCurrentWord ? '隐藏当前单词' : '显示当前单词' }}</button><p>{{ app.paused ? '练习已暂停，计时也已暂停。' : app.audioError ? '音频未能播放，请重播或跳过。' : app.speaking ? '正在播放原声语料' : app.prefs.interval === 0 ? '手动继续，按自己的节奏练习' : '音频结束后，按设定间隔继续' }}</p></div>
                <form v-if="app.session.mode === 'dictation'" class="corpus-answer-form" @submit.prevent="app.answered ? app.next() : app.submit()"><label class="sr-only" for="corpusAnswer">输入听到的语料</label><input id="corpusAnswer" ref="answerInput" v-model="app.answer" type="text" autocomplete="off" autocapitalize="off" spellcheck="false" maxlength="400" placeholder="输入拼写，按 Enter 提交" :disabled="app.paused || app.answered || Boolean(app.audioError)" /><button class="primary-button" type="submit" :disabled="app.paused || Boolean(app.audioError)">{{ app.answered ? '下一条' : '提交答案' }}<Icon name="right" :size="15" /></button></form>
                <p v-if="app.feedback" class="corpus-feedback" :class="{ incorrect: !app.feedback.correct }" role="status">{{ app.feedback.timedOut ? '上一题超时，正确答案：' : app.feedback.correct ? '回答正确：' : '正确答案：' }}<strong>{{ app.feedback.word }}</strong></p>
                <div v-if="app.audioError" class="corpus-audio-error" role="alert"><p>{{ app.audioError }}</p><button class="secondary-button" @click="app.skipAudio">跳过这条音频</button></div>
                <div class="corpus-transport"><button v-if="app.session.mode === 'listen'" class="text-button" :disabled="app.session.index === 0" @click="app.previous"><Icon name="left" :size="17" />上一条</button><button v-else class="text-button" :disabled="app.answered || app.paused || Boolean(app.audioError)" @click="app.reveal"><Icon name="eye" :size="16" />显示答案</button><button class="secondary-button" @click="app.togglePause"><Icon :name="app.paused ? 'play' : 'pause'" :size="15" />{{ app.paused ? '继续练习' : '暂停练习' }}</button><button class="text-button" :disabled="app.session.mode === 'dictation' && !app.answered" @click="app.next">{{ app.session.index === app.session.items.length - 1 ? '完成本轮' : '下一条' }}<Icon name="right" :size="17" /></button></div>
                <div class="corpus-current-actions"><button class="text-button" :disabled="app.currentRecord.errorLevel >= 10" @click="app.changeLevel(app.current, 1)"><Icon name="star" :size="14" />错误等级＋1</button><button class="text-button" :disabled="!app.currentRecord.errorLevel" @click="app.changeLevel(app.current, -1)">等级－1</button><span>{{ app.currentRecord.errorLevel }} / 10</span><button class="text-button corpus-end" @click="app.end">结束练习</button></div>
              </template>
            </section>
            <aside class="corpus-session-panel content-panel" :class="{ collapsed: !app.prefs.progressExpanded }"><button class="panel-heading corpus-session-toggle" :aria-expanded="app.prefs.progressExpanded" aria-controls="corpusSessionProgress" :aria-label="app.prefs.progressExpanded ? '隐藏本轮进度' : '展开本轮进度'" @click="app.toggleProgress"><span><Icon name="chart" :size="16" />本轮进度</span><span>{{ app.prefs.progressExpanded ? '隐藏' : '展开' }}<Icon name="down" :size="14" /></span></button><div v-show="app.prefs.progressExpanded" id="corpusSessionProgress" class="corpus-session-body"><div class="corpus-progress-ring" :style="{ '--progress': percent + '%' }"><div><strong>{{ percent }}<small>%</small></strong><span>{{ app.session.mode === 'listen' ? '听音进度' : '已完成' }}</span></div></div><div class="corpus-session-metrics"><div><span>本轮语料</span><strong>{{ app.session.items.length || app.group?.items.length || 0 }}</strong></div><template v-if="app.session.mode === 'dictation'"><div><span>已答对</span><strong>{{ app.correctCount }}</strong></div><div><span>待巩固</span><strong>{{ app.wrongItems.length }}</strong></div></template><template v-else><div><span>当前循环</span><strong>{{ app.session.loop }} / {{ app.session.loops }}</strong></div><div><span>每词播放</span><strong>{{ app.session.options.repeat || app.prefs.repeat }} 次</strong></div></template></div><p class="corpus-session-hint">{{ app.session.mode === 'listen' ? '听音模式专注播放，不写入正确率或错词。' : '答错、超时或显示答案，都会记入错词本。' }}</p></div></aside>
          </div>
          <section v-if="app.session.items.length && app.status !== 'idle'" class="content-panel corpus-queue"><div class="section-heading"><div><h2>本轮语料<span class="subtle-count">{{ app.session.items.length }}</span></h2><p>答对的语料会标记；听写时默认隐藏拼写。</p></div><button class="text-button" @click="app.toggleWords"><Icon name="eye" :size="15" />{{ app.prefs.showWords ? '隐藏语料' : '显示语料' }}</button></div><div class="corpus-queue-grid"><div v-for="(word, index) in app.session.items.slice(0, app.visibleCount)" :key="word.key" :class="{ current: app.active && app.session.index === index, correct: app.session.answers.get(index)?.correct, wrong: app.session.answers.has(index) && !app.session.answers.get(index)?.correct }"><span>{{ String(index + 1).padStart(2, '0') }}</span><strong>{{ app.prefs.showWords || app.session.answers.has(index) ? word.word : '••••••' }}</strong><Icon v-if="app.session.answers.get(index)?.correct" name="check" :size="14" /><Icon v-else-if="app.session.answers.has(index)" name="star" :size="13" /></div></div><button v-if="app.session.items.length > app.visibleCount" class="load-more" @click="app.visibleCount += 40">显示更多语料</button></section>
        </template>

        <section v-if="app.prefs.view === 'mistakes'" class="content-panel corpus-mistake-view">
          <div class="section-heading"><div><div class="eyebrow">A FEW MORE LISTENS</div><h2>把没听清的，再听一遍<span class="subtle-count">{{ app.mistakes.length }}</span></h2><p>同一条语料按分组分别记录，错误等级最高为 10。</p></div><button class="primary-button" :disabled="!app.filteredMistakes.length" @click="app.startMistakes"><Icon name="refresh" :size="16" />{{ app.selectedCount ? `练习选中 ${app.selectedCount} 条` : '练习当前列表' }}</button></div>
          <div class="corpus-mistake-toolbar"><label class="corpus-mistake-search"><Icon name="search" :size="17" /><input v-model="app.mistakeSearch" type="search" placeholder="搜索错词" aria-label="搜索错词" @input="app.visibleCount = 40" /></label><Select v-model="app.mistakeFilter" :options="mistakeFilters" option-label="label" option-value="value" checkmark aria-label="错词筛选" @change="app.visibleCount = 40" /><Select v-model="app.prefs.sort" :options="sortOptions" option-label="label" option-value="value" checkmark aria-label="错词排序" @change="app.savePrefs" /></div>
          <details class="corpus-group-filter"><summary>按分组筛选<span>{{ app.mistakeGroups.length ? `已选 ${app.mistakeGroups.length} 组` : '全部分组' }}</span><Icon name="down" :size="14" /></summary><label for="corpusMistakeGroups">点击勾选多个分组，可搜索编号或名称；不选择时显示全部分组。</label><MultiSelect input-id="corpusMistakeGroups" :model-value="app.mistakeGroups" :options="groupOptions" option-label="label" option-value="value" option-group-label="label" option-group-children="items" filter filter-placeholder="搜索分组编号或名称" reset-filter-on-hide display="chip" :max-selected-labels="3" selected-items-label="已选 {0} 个分组" placeholder="全部分组" show-clear aria-label="错词分组筛选" @update:model-value="app.mistakeGroups = $event || []; app.visibleCount = 40" /><button class="text-button" @click="app.mistakeGroups = []; app.visibleCount = 40">清除分组筛选</button></details>
          <div v-if="!app.filteredMistakes.length" class="empty-state"><span class="empty-icon"><Icon name="star" :size="29" /></span><h3>{{ app.mistakes.length ? '没有匹配的错词' : '还没有需要巩固的语料' }}</h3><p>{{ app.mistakes.length ? '调整搜索或筛选条件，看看其他错词。' : '听写中没听清的语料，会自动收在这里。' }}</p></div>
          <template v-else><div class="corpus-selection-tools"><span>找到 {{ app.filteredMistakes.length }} 条 · 已选 {{ app.selectedCount }} 条</span><div><button class="text-button" @click="app.selectAll()">全选</button><button class="text-button" @click="app.selectAll(true)">反选</button><button class="text-button" @click="app.selected.clear()">取消选择</button></div></div><div class="corpus-mistake-list"><article v-for="word in app.filteredMistakes.slice(0, app.visibleCount)" :key="word.key" class="corpus-mistake-row"><Checkbox binary :model-value="app.selected.has(word.key)" :aria-label="`选择 ${word.word}，分组 ${word.groupId}`" @update:model-value="app.toggleSelected(word.key)" /><div class="corpus-mistake-word"><strong>{{ word.word }}</strong><span>{{ word.groupId }} · {{ word.chapterTitle }} · {{ word.groupTitle }}</span><small v-if="app.records.get(word.key).recentAnswers.length">最近错答：{{ app.records.get(word.key).recentAnswers[0] }}</small></div><div class="corpus-mistake-count"><span>错误 {{ app.records.get(word.key).wrongCount }} 次</span><strong>正确率 {{ accuracy(app.records.get(word.key)) }}</strong></div><div class="corpus-error-level"><button :aria-label="`降低 ${word.word} 错误等级`" @click="app.changeLevel(word, -1)">－</button><span>{{ app.records.get(word.key).errorLevel }}<small> / 10</small></span><button :aria-label="`提高 ${word.word} 错误等级`" :disabled="app.records.get(word.key).errorLevel >= 10" @click="app.changeLevel(word, 1)">＋</button></div><div class="corpus-mistake-actions"><button class="icon-button" :disabled="!word.audio" :aria-label="`试听 ${word.word}`" @click="app.preview(word)"><Icon name="volume" :size="19" /></button><button class="icon-button" :aria-label="`移出错词本 ${word.word}`" @click="app.removeMistake(word)"><Icon name="close" :size="17" /></button></div></article></div><button v-if="app.filteredMistakes.length > app.visibleCount" class="load-more" @click="app.visibleCount += 40">显示更多错词</button></template>
        </section>

        <section v-if="app.prefs.view === 'stats'" class="corpus-stats">
          <div class="section-heading"><div><div class="eyebrow">HEAR YOUR PROGRESS</div><h2>听得更清楚的每一天</h2><p>完整分组的听写成绩按天汇总，听音与错词复练不计入。</p></div></div><label class="corpus-stats-select" for="corpusStatsGroup">查看分组<Select input-id="corpusStatsGroup" v-model="app.prefs.statsGroup" :options="groupOptions" option-label="label" option-value="value" option-group-label="label" option-group-children="items" filter filter-placeholder="搜索分组编号或名称" reset-filter-on-hide checkmark aria-label="查看分组" @change="app.savePrefs" /></label>
          <div class="stats-grid corpus-stats-cards"><article><span><Icon name="check" :size="18" />完整练习</span><strong>{{ app.scoreSummary.sessions }}<small> 次</small></strong><p>完成所选分组的全部听写</p></article><article><span><Icon name="chart" :size="18" />累计正确率</span><strong>{{ app.scoreSummary.total ? Math.round(app.scoreSummary.correct / app.scoreSummary.total * 1000) / 10 : 0 }}<small>%</small></strong><p>答对 {{ app.scoreSummary.correct }} / {{ app.scoreSummary.total }} 条</p></article><article><span><Icon name="star" :size="18" />最好成绩</span><strong>{{ app.scoreSummary.best }}<small>%</small></strong><p>所选分组的单轮最高正确率</p></article></div>
          <div v-if="!app.scoreRows.length" class="content-panel empty-state"><Icon name="chart" :size="32" /><h3>还没有完整章节成绩</h3><p>选中一个分组并完成全部听写，成绩就会出现在这里。</p><button class="secondary-button" @click="app.showView('practice')">回到语料练习<Icon name="right" :size="16" /></button></div>
          <template v-else><section class="content-panel corpus-chart"><div class="section-heading"><div><h2>正确率变化</h2><p>最近 14 个练习日，同一天多轮按答题量计算正确率。</p></div><span class="chart-legend"><i></i>每日正确率</span></div><svg viewBox="0 0 640 220" role="img" :aria-label="graphRows.map(row => `${row.day}正确率${row.accuracy}%`).join('，')"><g v-for="tick in [0, 50, 100]" :key="tick"><line x1="44" :y1="184 - tick * 1.52" x2="596" :y2="184 - tick * 1.52" class="corpus-chart-grid" /><text x="8" :y="188 - tick * 1.52">{{ tick }}%</text></g><polyline :points="graphPoints" class="corpus-chart-line" /><circle v-for="row in graphRows" :key="row.day" :cx="row.x" :cy="row.y" r="4"><title>{{ row.day }} · {{ row.accuracy }}%</title></circle><text x="44" y="212">{{ graphRows[0].day.slice(5) }}</text><text x="596" y="212" text-anchor="end">{{ graphRows.at(-1).day.slice(5) }}</text></svg></section><section class="content-panel corpus-score-history"><div class="section-heading"><div><h2>每日练习记录</h2><p>汇总保留练习次数、累计成绩和单轮最好成绩。</p></div></div><div class="corpus-score-table"><div class="corpus-score-row corpus-score-header"><span>日期</span><span>完整练习</span><span>正确率</span><span>最好成绩</span></div><div v-for="row in app.scoreRows.slice().reverse().slice(0, app.visibleCount)" :key="row.day" class="corpus-score-row"><strong>{{ row.day }}</strong><span>{{ row.sessions }} 次</span><span>{{ Math.round(row.correct / row.total * 1000) / 10 }}%</span><span>{{ row.best }}%</span></div></div><button v-if="app.scoreRows.length > app.visibleCount" class="load-more" @click="app.visibleCount += 40">显示更多记录</button></section></template>
        </section>
      </template>
      <footer class="page-footer"><span>王璐语料库机考 2 版<span class="footer-divider">/</span>仅供学习交流与内部使用</span><span v-if="app.prefs.view === 'practice'" class="keyboard-hints"><kbd>↑</kbd>重播<kbd>←</kbd><kbd>→</kbd>切换<span>·</span><kbd>Space</kbd>暂停／继续</span></footer>
    </main>
    <dialog ref="settings" class="settings-dialog" aria-labelledby="corpusSettingsTitle"><div class="dialog-heading"><div><div class="eyebrow">YOUR LISTENING RECORDS</div><h2 id="corpusSettingsTitle">听力学习记录</h2></div><button class="icon-button" aria-label="关闭听力学习记录" @click="settings.close()"><Icon name="close" /></button></div><div class="dialog-body"><section class="storage-details"><h3><Icon name="storage" :size="17" />浏览器存储</h3><p>设置、错词与成绩仅保存在当前浏览器。</p><dl><div><dt>保存方式</dt><dd>{{ app.storage.mode }}</dd></div><div><dt>学习记录占用</dt><dd>{{ formatBytes(app.storageSizes.total) }}</dd></div><div><dt>最大单条记录</dt><dd>{{ formatBytes(app.storageSizes.largest) }}<span> / 8 KiB</span></dd></div><div><dt>本地音频覆盖</dt><dd>{{ availableCount }} / {{ library.words.length }}</dd></div><div v-if="storageEstimate?.quota"><dt>来源可用空间估算</dt><dd>{{ formatBytes(Math.max(0, storageEstimate.quota - (storageEstimate.usage || 0))) }}</dd></div></dl><p class="storage-explanation">记录按词条和日期分开保存。同来源旧记录可读取，原记录保留；旧本地文件与不同地址之间的记录互不共享。音频不缓存到数据库。</p><button v-if="app.storage.state === 'error'" class="secondary-button" @click="app.retrySave">重试保存</button></section></div><div class="dialog-footer"><button class="primary-button" @click="settings.close()">完成<Icon name="check" :size="16" /></button></div></dialog>
    <Transition name="toast"><div v-if="app.notice" class="toast-message" role="status">{{ app.notice }}</div></Transition>
  </div>
</template>
